name: Build iOS Project

on:
  pull_request:
    branches: [ "dev" ]

jobs: 
  build:
    name: Build app
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: ./.github/build.sh