name: Build iOS Project

on:
  pull_request:
    branches: [ "dev" ]

jobs: 
  build:
    name: Build app
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Select Swift and Xcode
        uses: apple/setup-swift@latest
        with:
          xcode-version: '15.1'

      - name: Build
        run: ./.github/build.sh